/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Dashboard": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DashboardPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbBackups": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "KalshiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KalshiPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}