# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        service: str
        type: str
        url: str
    class ApiToken:
        type: str
        value: str
    class App:
        name: str
        stage: str
    class Dashboard:
        type: str
        url: str
    class DashboardPassword:
        type: str
        value: str
    class DbBackups:
        name: str
        type: str
    class KalshiApiKey:
        type: str
        value: str
    class KalshiPrivateKey:
        type: str
        value: str
    class Vpc:
        type: str

